name: Build Library
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun build ./index.ts --outdir ./build
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          path:
            build
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3       
